# Generated by Django 2.0.1 on 2018-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomic_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomicprofile',
            name='middle_init',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
