# Generated by Django 2.0.1 on 2018-03-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathogenicity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathogenicity',
            old_name='oncotatoroutput',
            new_name='id',
        ),
    ]
