# Generated by Django 2.0.1 on 2018-02-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathogenicity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathogenicity',
            name='oncotatoroutput',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pathogenicity.OncotatorOutput'),
        ),
    ]
